In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("MNRAS")

In [3]:
import ellipsoid3d

In [4]:
from ellipsoid3d.features import ellipsoid_estimation

In [5]:
from ellipsoid3d.models import model_ellipsoid

In [22]:
uniform_ellipsoid_shell = model_ellipsoid.uniform_ellipsoid_shell(1,1,1, n_points=100000)
uniform_ellipsoid = model_ellipsoid.uniform_ellipsoid(1,1,1, n_points=10000000)

In [26]:
ellipsoid_estimation.reduced_iterative_tensor_shell(uniform_ellipsoid, [0,0,0], 0.8,1.5)

Number of particles in shell:  2555733
[[ 0.70929224 -0.64717445  0.27940965]
 [-0.70346043 -0.67529672  0.22162526]
 [-0.04525422  0.35375071  0.93424434]]
projection matrix [[ 0.70929224 -0.64717445  0.27940965]
 [-0.70346043 -0.67529672  0.22162526]
 [-0.04525422  0.35375071  0.93424434]]


(True,
 [923.4333017346859, 922.973393600322, 922.563847087715],
 [array([ 1.00000000e+00, -4.53781963e-17,  1.40903679e-17]),
  array([-6.23848600e-17,  1.00000000e+00,  3.72534911e-17]),
  array([ 6.68649281e-18, -4.19700814e-17,  1.00000000e+00])])