In [326]:
%load_ext autoreload
%autoreload 2

import pyvista as pv
import numpy as np
from astropy.table import Table

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [327]:
from src.features import calculate_shape as cs

In [328]:
gal_table = Table.read("../data/interim/gal_table.fits")
cen_x = gal_table[gal_table['group_id']==5491][0]['pos_x']
cen_y = gal_table[gal_table['group_id']==5491][0]['pos_y']
cen_z = gal_table[gal_table['group_id']==5491][0]['pos_z']
cen = np.array([cen_x, cen_y, cen_z])

In [329]:
import deepdish as dd
cutout = dd.io.load('../data/raw/cutout_halo_dm_5491.h5')
points = cutout['PartType1']['Coordinates']

In [330]:
# import numpy as np

# # Choose the semi-axes of the ellipsoid
# a = 100.0  # semi-axis length in x-direction
# b = 1.0  # semi-axis length in y-direction
# c = 1.0  # semi-axis length in z-direction

# # Generate uniformly distributed points within a unit sphere
# u = np.random.rand(10000)
# v = np.random.rand(10000)
# theta = 2 * np.pi * u
# phi = np.arccos(2 * v - 1)
# x = np.sin(phi) * np.cos(theta)
# y = np.sin(phi) * np.sin(theta)
# z = np.cos(phi)

# # Scale the coordinates of the points by the semi-axes of the ellipsoid
# points = np.vstack((a*x, b*y, c*z)).T
# print(points)
# cen=0,0,0

In [331]:
print(cen-points[0])

[-0.1263475   0.23311255  0.43173037]


In [332]:
# converge, length, axes = cs.quad_moment(points, cen, np.ones(len(points)))
converge, length, axes = cs.quad_moment(points, cen, np.ones(len(points)))

10165.438143737487
21802.066237104296
22462.307273560455
Number of particles inside virial radius is  136165
[[42216.63357481  7889.99875421 -1559.06893714]
 [ 7889.99875421 45204.97652419 10099.60860341]
 [-1559.06893714 10099.60860341 48743.389901  ]]
a,b,c in the first iteration
241.49282588677897 214.78266857991892 178.08599137188324
lx in the first iteration [0.2696081  0.68413708 0.67769309]
ly in the first iteration [-0.770917   -0.26838329  0.57763084]
lz in the first iteration [ 0.57706017 -0.67817908  0.4550546 ]
P_axis: [[ 0.2696081   0.68413708  0.67769309]
 [-0.770917   -0.26838329  0.57763084]
 [ 0.57706017 -0.67817908  0.4550546 ]]
a, b, c  225.5993151306028 189.76411473425574 147.01587656193598
q_cur, s_cur 0.7374380200237366 0.8893956488819971
P_axis: [[ 0.9999403   0.00824091 -0.00717516]
 [-0.00821433  0.99995932  0.003725  ]
 [ 0.00720556 -0.00366584  0.99996732]]
a, b, c  218.43286708449904 179.14333430373011 135.27956176355235
q_cur, s_cur 0.6516680978256796 0.841

In [333]:
print(length)
print(axes)

[213.04542549720375, 171.20912066069283, 127.2356514365935]
[array([ 0.24458991,  0.7709844 , -0.58801261]), array([0.69141338, 0.28648435, 0.66323016]), array([ 0.67979652, -0.56877919, -0.46299775])]


In [334]:
pl = pv.Plotter()
SCALE = 1
x_arrow = pv.Arrow(start = (0,0,0), direction = axes[0], scale=SCALE*length[0])
y_arrow = pv.Arrow(start = (0,0,0), direction = axes[1], scale=SCALE*length[1])
z_arrow = pv.Arrow(start = (0,0,0), direction = axes[2], scale=SCALE*length[2])
actor = pl.add_points(points-cen, color='white', opacity=0.01)
actor = pl.add_mesh(x_arrow, color='red')
actor = pl.add_mesh(y_arrow, color='green')
actor = pl.add_mesh(z_arrow, color='blue')
pl.show()

Widget(value="<iframe src='http://localhost:56012/index.html?ui=P_0x1e261da90_32&reconnect=auto' style='width:…